### ISSUE TITLE
Frontend: GUI - Statistiken

### ISSUE THREAD

**Issue by JormaBork** [lrnzkck/carcosts_app#14]

**Comment by lrnzkck** [comment]
4 Sachen: Tankdaten (Liste, Gucken wegen Summe!), gleiches für Werkstatt, Pflege
Noch zu realisieren: Gesamtstatistik anzeigen, View überlegen, Logik bauen.
-> Listet alle möglichen Daten auf.
Controller sind fertig.

**Comment by JormaBork** [comment]
Alles fertig :-)
