### ISSUE TITLE
Typo fixen

### ISSUE THREAD

**Issue by erikhofer** [lrnzkck/carcosts_app#30]
https://github.com/lrnzkck/carcosts_app/blob/8d41e7ae5fd3f7b3d480c4670dab5b537c8ff710/CarCostApp/mobile/src/main/java/de/lorenzkock/carcost/carcostapp/adapter/CarListAdapter.java#L42

**Comment by Kibia** [comment]
Prio: 1

**Comment by lrnzkck** [comment]
Thanks for helping! Your issue had a big impact on our new thinking!
